### ISSUE TITLE
Problems with special caracters

### ISSUE THREAD

**Issue by jeanpablojp** [GideonLeGrange/mikrotik-java#17]
When I try to add a username that contains a special caracter like 'çãáõ' the api is replacing to '?'.
But when i put this special caracteres direct in the winbox it works ok.

Do you have an idea about what should be the problem???

**Comment by GideonLeGrange** [comment]
Sorry for the late reply. 

It is most likely not my code breaking this, but I'll check any way. 

I'll get back to you. 

Gideon

**Comment by GideonLeGrange** [comment]
I understand that you can add users like that through Winbox but the RouterOS web interface doesn't allow it (see image). You can't do it from the telnet/ssh command line either, so I think it is best not to use special characters in usernames. 

![screen shot 2015-03-28 at 18 02 09](https://cloud.githubusercontent.com/assets/1131028/6881731/a7865556-d574-11e4-9099-a0ee690e3138.png)

I also tried it with the Java API: 

```java
con.execute("/user/add name=çãáõ");
```

I get the following result:

```
Exception in thread "main" me.legrange.mikrotik.MikrotikApiException: failure: invalid user name
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.getResults(ApiConnectionImpl.java:510)
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.access$100(ApiConnectionImpl.java:472)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:137)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:108)
	at examples.Example9.test(Example9.java:22)
```

So I think that if this work for you in Winbox, it is Winbox, or potentially an older version of RouterOS that you're using that is an anomaly. 

I hope this helps.
