### ISSUE TITLE
Problem with " " (white space) for adding user hotspot

### ISSUE THREAD

**Issue by rudiw** [GideonLeGrange/mikrotik-java#38]
Relates to [https://github.com/GideonLeGrange/mikrotik-java/issues/3](https://github.com/GideonLeGrange/mikrotik-java/issues/3)

Environment:
```
<dependency>
	<groupId>me.legrange</groupId>
	<artifactId>mikrotik</artifactId>
	<version>3.0.1</version>
</dependency>

Router OS 6.35.4

hAP lite RB941-2nD-TC
```

The code **WITH** With Space:
```
connection.execute(String.format("/ip/hotspot/user/add name=%s password=%s profile=%s", "rudi wijaya", "rudi wijaya", "default"));
```
and I got error:
```
me.legrange.mikrotik.MikrotikApiException: unknown parameter
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.getResults(ApiConnectionImpl.java:471)
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.access$100(ApiConnectionImpl.java:425)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:110)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:68)
	at com.rudiwijaya.payment.dao.MikroTikManagerImpl.createUserHotspot(MikroTikManagerImpl.java:78)
	at com.rudiwijaya.payment.dao.MikroTikManagerTest.addUserHotspot(MikroTikManagerTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: me.legrange.mikrotik.impl.ApiCommandException: unknown parameter
	at me.legrange.mikrotik.impl.ApiConnectionImpl$Processor.run(ApiConnectionImpl.java:257)
```

If mycode (with **NO White Space**):
```
connection.execute(String.format("/ip/hotspot/user/add name=%s password=%s profile=%s","rudiwijaya", "rudiwijaya", "default"));
```
There was no problem..

**Comment by GideonLeGrange** [comment]
I don't think this is related to #3, I think it is the same as #39, which wasn't a bug. 

You need to handle string quoting, like so:

```java
connection.execute(String.format("/ip/hotspot/user/add name=\"%s\" password=\"%s\" profile=%s", "rudi wijaya", "rudi wijaya", "default")); 
```

The command that will then be generated will be:

```
/ip/hotspot/user/add name="rudi wijaya" password="rudi wijaya" profile=default
```

Let me know if that solves it please.

**Comment by rudiw** [comment]
It is not works too.. Sorry, I forgot to add the code like that before.. The error is `missed with argument "\"`

**Comment by GideonLeGrange** [comment]
Sorry, meant to say #33, not #39. 

You have more than one problem here. If you have values with spaces in, you need to quote them. That is irrespective of it it solves this particular problem.

**Comment by rudiw** [comment]
I will try soon and report too.. @GideonLeGrange :)

**Comment by GideonLeGrange** [comment]
Both of these work for me. 

```java
       con.execute("/ip/hotspot/user/add name=\"rudi wijaya\" password=\"rudi wijaya\" profile=default");
        
       con.execute(String.format("/ip/hotspot/user/add name=\"%s\" password=\"%s\" profile=default", "rudi wijaya", "rudi wijaya"));
```

**Comment by rudiw** [comment]
Very sorry I was late to give feed back, **it is works**. I did not know what happened with my eyes 2 days ago.. Thank you so much @GideonLeGrange
