### ISSUE TITLE
Unknown Parameter for Adding User Hotspot Profile

### ISSUE THREAD

**Issue by rudiw** [GideonLeGrange/mikrotik-java#39]
I want to add User Hotspot Profile with some values:

1. name
2. address pool
3. mac cookie timeout

Environment:
```
<dependency>
    <groupId>me.legrange</groupId>
    <artifactId>mikrotik</artifactId>
    <version>3.0.1</version>
</dependency>

Router OS 6.35.4

hAP lite RB941-2nD-TC
```
The code:
```
connection.execute(String.format("/ip/hotspot/user/profile/add name=%s add=%s", "userprofile", "rudipool"));
```

and I got error:
```
me.legrange.mikrotik.MikrotikApiException: unknown parameter
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.getResults(ApiConnectionImpl.java:471)
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.access$100(ApiConnectionImpl.java:425)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:110)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:68)
	at com.rudiwijaya.payment.dao.MikroTikManagerImpl.createHotspotUserProfile(MikroTikManagerImpl.java:92)
	at com.rudiwijaya.payment.dao.MikroTikManagerTest.addUserHotspotProfile(MikroTikManagerTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: me.legrange.mikrotik.impl.ApiCommandException: unknown parameter
	at me.legrange.mikrotik.impl.ApiConnectionImpl$Processor.run(ApiConnectionImpl.java:257)
```

But, I has code like:
```
connection.execute(String.format("/ip/hotspot/user/profile/add name=%s","userprofile"));
```
there was no error and it was created.

And in the `terminal` for script:
```
ip hotspot user profile add name=hsptest add=default mac="5d 00:00:00"
```
uses fields: **name**, **add**, and **mac**. It was success with specified 3 values..

**Comment by rudiw** [comment]
**There is no " " (white space)**
`MikrotikApiException: unknown parameter`

Code with **" " (whit space)** above running in **Terminal Router OS**

**Comment by GideonLeGrange** [comment]
That is not valid. The API is **not** the command line. There is no auto-completion and you need to write the commands out. "add" will not be auto-completed to "address-pool" and "mac" will not be auto-completed to "mac-cookie-timeout".

This code works:

```java
 con.execute("/ip/hotspot/user/profile/add name=userprofile address-pool=mypool  mac-cookie-timeout=7d"); 
```

On my router:

```
[router] /ip hotspot user> profile print   
Flags: * - default 
 0 * name="default" idle-timeout=none keepalive-timeout=2m status-autorefresh=1m shared-users=1 add-mac-cookie=yes mac-cookie-timeout=3d address-list="" 
     transparent-proxy=no 

 1   name="userprofile" address-pool=mypool idle-timeout=none keepalive-timeout=2m status-autorefresh=1m shared-users=1 add-mac-cookie=yes mac-cookie-timeout=1w 
     address-list="" transparent-proxy=no 
```

**Comment by rudiw** [comment]
Very sorry I was late to give feed back, **it is works**. Thank you so much @GideonLeGrange for giving me the fields..
