### ISSUE TITLE
No support for /interface/monitor-traffic?

### ISSUE THREAD

**Issue by kdmux** [GideonLeGrange/mikrotik-java#52]
Hello! I am trying to implement a tool that reads the total traffic of a Bridge on a Mikrotik Device, however when i try to do the following
`List<Map<String, String>> res = api.execute("/interface/monitor-traffic/wlan-bridge/once");`
I get the following error:
`me.legrange.mikrotik.MikrotikApiException: no such command prefix
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.getResults(ApiConnectionImpl.java:472)
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.access$100(ApiConnectionImpl.java:426)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:110)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:68)
	at at.klu.nos.mikrotik.CAPsMAN.pollUsage(CAPsMAN.java:222)
	at at.klu.nos.context.BackgroundContext.lambda$1(BackgroundContext.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

**Comment by GideonLeGrange** [comment]
I think the syntax of your command is wrong. From the command line I can do this:

`/interface monitor-traffic interface=ether5-slave-local once `

When using the API this should translate to:

`/interface/monitor-traffic interface=ether5-slave-local once`

When going from command line syntax to API syntax you replace the spaces in the command with '/' but the spaces between parameters are kept. The command in this case is '/interface/monitor-traffic' 

Hope that helps.
