### ISSUE TITLE
Problem to send profile exchange command

### ISSUE THREAD

**Issue by antonioGabrielGomes** [GideonLeGrange/mikrotik-java#64]
Hello. I'm having trouble sending a profile exchange command to the router.

public void alterProfile(String name) throws Exception {		
		ApiConnection con = null;
		String stmt = "/ppp/secret/set profile=default " + name;

		try {			
			con = ConnectionFactoryMikrotik.connect();			
	   		con.execute(stmt);           
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			ConnectionFactoryMikrotik.disconnect(con);
		}

	}

Do you know if I'm miscalculating the syntax?

**Comment by antonioGabrielGomes** [comment]
Exception: 
me.legrange.mikrotik.MikrotikApiException: unknown parameter
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.getResults(ApiConnectionImpl.java:476)
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.access$100(ApiConnectionImpl.java:430)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:114)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:72)
