### ISSUE TITLE
Failed to login if password contain !

### ISSUE THREAD

**Issue by jharahuld** [GideonLeGrange/mikrotik-java#73]
Unable to login via api getting "invalid user name or password (6)" exception if password contains exclamation character.

`Exception in thread "main" me.legrange.mikrotik.MikrotikApiException: invalid user name or password (6)
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.getResults(ApiConnectionImpl.java:476)
	at me.legrange.mikrotik.impl.ApiConnectionImpl$SyncListener.access$100(ApiConnectionImpl.java:430)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:114)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.execute(ApiConnectionImpl.java:72)
	at me.legrange.mikrotik.impl.ApiConnectionImpl.login(ApiConnectionImpl.java:58)
	at com.h8.mktapi305test.App.main(App.java:18)

Caused by: me.legrange.mikrotik.impl.ApiCommandException: invalid user name or password (6)
	at me.legrange.mikrotik.impl.ApiConnectionImpl$Processor.run(ApiConnectionImpl.java:267)`

**Comment by GideonLeGrange** [comment]
Can you please try this with the latest version, **3.0.6.** I think this was fixed in #67 which I merged in October but which I forgot to make a new release for and released this morning.  

I tested this this morning with password "123!456" and "!123456" and it does seem to be fixed. 

Gideon
